#include <catch2/catch_test_macros.hpp>

TEST_CASE("Default exception", "[default]") {
    REQUIRE((1 ==1));
}

